// <auto-generated />
using System;
using IQTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IQTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IQTest.Core.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("IQTest.Core.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Resources/QuestionOptionImages/q1o1.png",
                            IsAnswer = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "Resources/QuestionOptionImages/q1o2.png",
                            IsAnswer = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "Resources/QuestionOptionImages/q1o3.png",
                            IsAnswer = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Resources/QuestionOptionImages/q1o4.png",
                            IsAnswer = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "Resources/QuestionOptionImages/q1o5.png",
                            IsAnswer = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "Resources/QuestionOptionImages/q1o6.png",
                            IsAnswer = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "Resources/QuestionOptionImages/q2o1.png",
                            IsAnswer = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "Resources/QuestionOptionImages/q2o2.png",
                            IsAnswer = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "Resources/QuestionOptionImages/q2o3.png",
                            IsAnswer = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "Resources/QuestionOptionImages/q2o4.png",
                            IsAnswer = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "Resources/QuestionOptionImages/q2o5.png",
                            IsAnswer = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "Resources/QuestionOptionImages/q2o6.png",
                            IsAnswer = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "Resources/QuestionOptionImages/q3o1.png",
                            IsAnswer = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "Resources/QuestionOptionImages/q3o2.png",
                            IsAnswer = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "Resources/QuestionOptionImages/q3o3.png",
                            IsAnswer = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "Resources/QuestionOptionImages/q3o4.png",
                            IsAnswer = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "Resources/QuestionOptionImages/q3o5.png",
                            IsAnswer = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "Resources/QuestionOptionImages/q3o6.png",
                            IsAnswer = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "Resources/QuestionOptionImages/q4o1.png",
                            IsAnswer = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "Resources/QuestionOptionImages/q4o2.png",
                            IsAnswer = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "Resources/QuestionOptionImages/q4o3.png",
                            IsAnswer = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "Resources/QuestionOptionImages/q4o4.png",
                            IsAnswer = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "Resources/QuestionOptionImages/q4o5.png",
                            IsAnswer = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "Resources/QuestionOptionImages/q4o6.png",
                            IsAnswer = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "Resources/QuestionOptionImages/q5o1.png",
                            IsAnswer = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "Resources/QuestionOptionImages/q5o2.png",
                            IsAnswer = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "Resources/QuestionOptionImages/q5o3.png",
                            IsAnswer = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "Resources/QuestionOptionImages/q5o4.png",
                            IsAnswer = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "Resources/QuestionOptionImages/q5o5.png",
                            IsAnswer = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "Resources/QuestionOptionImages/q5o6.png",
                            IsAnswer = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "Resources/QuestionOptionImages/q6o1.png",
                            IsAnswer = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "Resources/QuestionOptionImages/q6o2.png",
                            IsAnswer = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "Resources/QuestionOptionImages/q6o3.png",
                            IsAnswer = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "Resources/QuestionOptionImages/q6o4.png",
                            IsAnswer = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "Resources/QuestionOptionImages/q6o5.png",
                            IsAnswer = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "Resources/QuestionOptionImages/q6o6.png",
                            IsAnswer = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 37,
                            ImagePath = "Resources/QuestionOptionImages/q7o1.png",
                            IsAnswer = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 38,
                            ImagePath = "Resources/QuestionOptionImages/q7o2.png",
                            IsAnswer = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 39,
                            ImagePath = "Resources/QuestionOptionImages/q7o3.png",
                            IsAnswer = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 40,
                            ImagePath = "Resources/QuestionOptionImages/q7o4.png",
                            IsAnswer = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 41,
                            ImagePath = "Resources/QuestionOptionImages/q7o5.png",
                            IsAnswer = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 42,
                            ImagePath = "Resources/QuestionOptionImages/q7o6.png",
                            IsAnswer = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 43,
                            ImagePath = "Resources/QuestionOptionImages/q8o1.png",
                            IsAnswer = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 44,
                            ImagePath = "Resources/QuestionOptionImages/q8o2.png",
                            IsAnswer = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 45,
                            ImagePath = "Resources/QuestionOptionImages/q8o3.png",
                            IsAnswer = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 46,
                            ImagePath = "Resources/QuestionOptionImages/q8o4.png",
                            IsAnswer = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 47,
                            ImagePath = "Resources/QuestionOptionImages/q8o5.png",
                            IsAnswer = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 48,
                            ImagePath = "Resources/QuestionOptionImages/q8o6.png",
                            IsAnswer = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 49,
                            ImagePath = "Resources/QuestionOptionImages/q9o1.png",
                            IsAnswer = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 50,
                            ImagePath = "Resources/QuestionOptionImages/q9o2.png",
                            IsAnswer = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 51,
                            ImagePath = "Resources/QuestionOptionImages/q9o3.png",
                            IsAnswer = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 52,
                            ImagePath = "Resources/QuestionOptionImages/q9o4.png",
                            IsAnswer = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 53,
                            ImagePath = "Resources/QuestionOptionImages/q9o5.png",
                            IsAnswer = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 54,
                            ImagePath = "Resources/QuestionOptionImages/q9o6.png",
                            IsAnswer = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 55,
                            ImagePath = "Resources/QuestionOptionImages/q10o1.png",
                            IsAnswer = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 56,
                            ImagePath = "Resources/QuestionOptionImages/q10o2.png",
                            IsAnswer = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 57,
                            ImagePath = "Resources/QuestionOptionImages/q10o3.png",
                            IsAnswer = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 58,
                            ImagePath = "Resources/QuestionOptionImages/q10o4.png",
                            IsAnswer = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 59,
                            ImagePath = "Resources/QuestionOptionImages/q10o5.png",
                            IsAnswer = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 60,
                            ImagePath = "Resources/QuestionOptionImages/q10o6.png",
                            IsAnswer = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 61,
                            ImagePath = "Resources/QuestionOptionImages/q11o1.png",
                            IsAnswer = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 62,
                            ImagePath = "Resources/QuestionOptionImages/q11o2.png",
                            IsAnswer = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 63,
                            ImagePath = "Resources/QuestionOptionImages/q11o3.png",
                            IsAnswer = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 64,
                            ImagePath = "Resources/QuestionOptionImages/q11o4.png",
                            IsAnswer = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 65,
                            ImagePath = "Resources/QuestionOptionImages/q11o5.png",
                            IsAnswer = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 66,
                            ImagePath = "Resources/QuestionOptionImages/q11o6.png",
                            IsAnswer = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 67,
                            ImagePath = "Resources/QuestionOptionImages/q12o1.png",
                            IsAnswer = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 68,
                            ImagePath = "Resources/QuestionOptionImages/q12o2.png",
                            IsAnswer = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 69,
                            ImagePath = "Resources/QuestionOptionImages/q12o3.png",
                            IsAnswer = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 70,
                            ImagePath = "Resources/QuestionOptionImages/q12o4.png",
                            IsAnswer = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 71,
                            ImagePath = "Resources/QuestionOptionImages/q12o5.png",
                            IsAnswer = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 72,
                            ImagePath = "Resources/QuestionOptionImages/q12o6.png",
                            IsAnswer = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 73,
                            ImagePath = "Resources/QuestionOptionImages/q13o1.png",
                            IsAnswer = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 74,
                            ImagePath = "Resources/QuestionOptionImages/q13o2.png",
                            IsAnswer = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 75,
                            ImagePath = "Resources/QuestionOptionImages/q13o3.png",
                            IsAnswer = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 76,
                            ImagePath = "Resources/QuestionOptionImages/q13o4.png",
                            IsAnswer = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 77,
                            ImagePath = "Resources/QuestionOptionImages/q13o5.png",
                            IsAnswer = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 78,
                            ImagePath = "Resources/QuestionOptionImages/q13o6.png",
                            IsAnswer = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 79,
                            ImagePath = "Resources/QuestionOptionImages/q14o1.png",
                            IsAnswer = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 80,
                            ImagePath = "Resources/QuestionOptionImages/q14o2.png",
                            IsAnswer = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 81,
                            ImagePath = "Resources/QuestionOptionImages/q14o3.png",
                            IsAnswer = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 82,
                            ImagePath = "Resources/QuestionOptionImages/q14o4.png",
                            IsAnswer = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 83,
                            ImagePath = "Resources/QuestionOptionImages/q14o5.png",
                            IsAnswer = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 84,
                            ImagePath = "Resources/QuestionOptionImages/q14o6.png",
                            IsAnswer = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 85,
                            ImagePath = "Resources/QuestionOptionImages/q15o1.png",
                            IsAnswer = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 86,
                            ImagePath = "Resources/QuestionOptionImages/q15o2.png",
                            IsAnswer = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 87,
                            ImagePath = "Resources/QuestionOptionImages/q15o3.png",
                            IsAnswer = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 88,
                            ImagePath = "Resources/QuestionOptionImages/q15o4.png",
                            IsAnswer = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 89,
                            ImagePath = "Resources/QuestionOptionImages/q15o5.png",
                            IsAnswer = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 90,
                            ImagePath = "Resources/QuestionOptionImages/q15o6.png",
                            IsAnswer = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 91,
                            ImagePath = "Resources/QuestionOptionImages/q16o1.png",
                            IsAnswer = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 92,
                            ImagePath = "Resources/QuestionOptionImages/q16o2.png",
                            IsAnswer = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 93,
                            ImagePath = "Resources/QuestionOptionImages/q16o3.png",
                            IsAnswer = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 94,
                            ImagePath = "Resources/QuestionOptionImages/q16o4.png",
                            IsAnswer = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 95,
                            ImagePath = "Resources/QuestionOptionImages/q16o5.png",
                            IsAnswer = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 96,
                            ImagePath = "Resources/QuestionOptionImages/q16o6.png",
                            IsAnswer = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 97,
                            ImagePath = "Resources/QuestionOptionImages/q17o1.png",
                            IsAnswer = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 98,
                            ImagePath = "Resources/QuestionOptionImages/q17o2.png",
                            IsAnswer = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 99,
                            ImagePath = "Resources/QuestionOptionImages/q17o3.png",
                            IsAnswer = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 100,
                            ImagePath = "Resources/QuestionOptionImages/q17o4.png",
                            IsAnswer = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 101,
                            ImagePath = "Resources/QuestionOptionImages/q17o5.png",
                            IsAnswer = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 102,
                            ImagePath = "Resources/QuestionOptionImages/q17o6.png",
                            IsAnswer = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 103,
                            ImagePath = "Resources/QuestionOptionImages/q18o1.png",
                            IsAnswer = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 104,
                            ImagePath = "Resources/QuestionOptionImages/q18o2.png",
                            IsAnswer = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 105,
                            ImagePath = "Resources/QuestionOptionImages/q18o3.png",
                            IsAnswer = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 106,
                            ImagePath = "Resources/QuestionOptionImages/q18o4.png",
                            IsAnswer = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 107,
                            ImagePath = "Resources/QuestionOptionImages/q18o5.png",
                            IsAnswer = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 108,
                            ImagePath = "Resources/QuestionOptionImages/q18o6.png",
                            IsAnswer = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 109,
                            ImagePath = "Resources/QuestionOptionImages/q19o1.png",
                            IsAnswer = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 110,
                            ImagePath = "Resources/QuestionOptionImages/q19o2.png",
                            IsAnswer = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 111,
                            ImagePath = "Resources/QuestionOptionImages/q19o3.png",
                            IsAnswer = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 112,
                            ImagePath = "Resources/QuestionOptionImages/q19o4.png",
                            IsAnswer = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 113,
                            ImagePath = "Resources/QuestionOptionImages/q19o5.png",
                            IsAnswer = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 114,
                            ImagePath = "Resources/QuestionOptionImages/q19o6.png",
                            IsAnswer = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 115,
                            ImagePath = "Resources/QuestionOptionImages/q20o1.png",
                            IsAnswer = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 116,
                            ImagePath = "Resources/QuestionOptionImages/q20o2.png",
                            IsAnswer = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 117,
                            ImagePath = "Resources/QuestionOptionImages/q20o3.png",
                            IsAnswer = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 118,
                            ImagePath = "Resources/QuestionOptionImages/q20o4.png",
                            IsAnswer = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 119,
                            ImagePath = "Resources/QuestionOptionImages/q20o5.png",
                            IsAnswer = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 120,
                            ImagePath = "Resources/QuestionOptionImages/q20o6.png",
                            IsAnswer = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 121,
                            ImagePath = "Resources/QuestionOptionImages/q21o1.png",
                            IsAnswer = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 122,
                            ImagePath = "Resources/QuestionOptionImages/q21o2.png",
                            IsAnswer = true,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 123,
                            ImagePath = "Resources/QuestionOptionImages/q21o3.png",
                            IsAnswer = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 124,
                            ImagePath = "Resources/QuestionOptionImages/q21o4.png",
                            IsAnswer = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 125,
                            ImagePath = "Resources/QuestionOptionImages/q21o5.png",
                            IsAnswer = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 126,
                            ImagePath = "Resources/QuestionOptionImages/q21o6.png",
                            IsAnswer = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 127,
                            ImagePath = "Resources/QuestionOptionImages/q22o1.png",
                            IsAnswer = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 128,
                            ImagePath = "Resources/QuestionOptionImages/q22o2.png",
                            IsAnswer = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 129,
                            ImagePath = "Resources/QuestionOptionImages/q22o3.png",
                            IsAnswer = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 130,
                            ImagePath = "Resources/QuestionOptionImages/q22o4.png",
                            IsAnswer = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 131,
                            ImagePath = "Resources/QuestionOptionImages/q22o5.png",
                            IsAnswer = true,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 132,
                            ImagePath = "Resources/QuestionOptionImages/q22o6.png",
                            IsAnswer = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 133,
                            ImagePath = "Resources/QuestionOptionImages/q23o1.png",
                            IsAnswer = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 134,
                            ImagePath = "Resources/QuestionOptionImages/q23o2.png",
                            IsAnswer = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 135,
                            ImagePath = "Resources/QuestionOptionImages/q23o3.png",
                            IsAnswer = true,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 136,
                            ImagePath = "Resources/QuestionOptionImages/q23o4.png",
                            IsAnswer = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 137,
                            ImagePath = "Resources/QuestionOptionImages/q23o5.png",
                            IsAnswer = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 138,
                            ImagePath = "Resources/QuestionOptionImages/q23o6.png",
                            IsAnswer = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 139,
                            ImagePath = "Resources/QuestionOptionImages/q24o1.png",
                            IsAnswer = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 140,
                            ImagePath = "Resources/QuestionOptionImages/q24o2.png",
                            IsAnswer = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 141,
                            ImagePath = "Resources/QuestionOptionImages/q24o3.png",
                            IsAnswer = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 142,
                            ImagePath = "Resources/QuestionOptionImages/q24o4.png",
                            IsAnswer = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 143,
                            ImagePath = "Resources/QuestionOptionImages/q24o5.png",
                            IsAnswer = true,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 144,
                            ImagePath = "Resources/QuestionOptionImages/q24o6.png",
                            IsAnswer = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 145,
                            ImagePath = "Resources/QuestionOptionImages/q25o1.png",
                            IsAnswer = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 146,
                            ImagePath = "Resources/QuestionOptionImages/q25o2.png",
                            IsAnswer = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 147,
                            ImagePath = "Resources/QuestionOptionImages/q25o3.png",
                            IsAnswer = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 148,
                            ImagePath = "Resources/QuestionOptionImages/q25o4.png",
                            IsAnswer = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 149,
                            ImagePath = "Resources/QuestionOptionImages/q25o5.png",
                            IsAnswer = true,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 150,
                            ImagePath = "Resources/QuestionOptionImages/q25o6.png",
                            IsAnswer = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 151,
                            ImagePath = "Resources/QuestionOptionImages/q26o1.png",
                            IsAnswer = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 152,
                            ImagePath = "Resources/QuestionOptionImages/q26o2.png",
                            IsAnswer = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 153,
                            ImagePath = "Resources/QuestionOptionImages/q26o3.png",
                            IsAnswer = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 154,
                            ImagePath = "Resources/QuestionOptionImages/q26o4.png",
                            IsAnswer = true,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 155,
                            ImagePath = "Resources/QuestionOptionImages/q26o5.png",
                            IsAnswer = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 156,
                            ImagePath = "Resources/QuestionOptionImages/q26o6.png",
                            IsAnswer = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 157,
                            ImagePath = "Resources/QuestionOptionImages/q27o1.png",
                            IsAnswer = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 158,
                            ImagePath = "Resources/QuestionOptionImages/q27o2.png",
                            IsAnswer = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 159,
                            ImagePath = "Resources/QuestionOptionImages/q27o3.png",
                            IsAnswer = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 160,
                            ImagePath = "Resources/QuestionOptionImages/q27o4.png",
                            IsAnswer = true,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 161,
                            ImagePath = "Resources/QuestionOptionImages/q27o5.png",
                            IsAnswer = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 162,
                            ImagePath = "Resources/QuestionOptionImages/q27o6.png",
                            IsAnswer = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 163,
                            ImagePath = "Resources/QuestionOptionImages/q28o1.png",
                            IsAnswer = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 164,
                            ImagePath = "Resources/QuestionOptionImages/q28o2.png",
                            IsAnswer = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 165,
                            ImagePath = "Resources/QuestionOptionImages/q28o3.png",
                            IsAnswer = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 166,
                            ImagePath = "Resources/QuestionOptionImages/q28o4.png",
                            IsAnswer = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 167,
                            ImagePath = "Resources/QuestionOptionImages/q28o5.png",
                            IsAnswer = true,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 168,
                            ImagePath = "Resources/QuestionOptionImages/q28o6.png",
                            IsAnswer = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 169,
                            ImagePath = "Resources/QuestionOptionImages/q29o1.png",
                            IsAnswer = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 170,
                            ImagePath = "Resources/QuestionOptionImages/q29o2.png",
                            IsAnswer = true,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 171,
                            ImagePath = "Resources/QuestionOptionImages/q29o3.png",
                            IsAnswer = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 172,
                            ImagePath = "Resources/QuestionOptionImages/q29o4.png",
                            IsAnswer = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 173,
                            ImagePath = "Resources/QuestionOptionImages/q29o5.png",
                            IsAnswer = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 174,
                            ImagePath = "Resources/QuestionOptionImages/q29o6.png",
                            IsAnswer = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 175,
                            ImagePath = "Resources/QuestionOptionImages/q30o1.png",
                            IsAnswer = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 176,
                            ImagePath = "Resources/QuestionOptionImages/q30o2.png",
                            IsAnswer = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 177,
                            ImagePath = "Resources/QuestionOptionImages/q30o3.png",
                            IsAnswer = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 178,
                            ImagePath = "Resources/QuestionOptionImages/q30o4.png",
                            IsAnswer = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 179,
                            ImagePath = "Resources/QuestionOptionImages/q30o5.png",
                            IsAnswer = true,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 180,
                            ImagePath = "Resources/QuestionOptionImages/q30o6.png",
                            IsAnswer = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 181,
                            ImagePath = "Resources/QuestionOptionImages/q31o1.png",
                            IsAnswer = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 182,
                            ImagePath = "Resources/QuestionOptionImages/q31o2.png",
                            IsAnswer = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 183,
                            ImagePath = "Resources/QuestionOptionImages/q31o3.png",
                            IsAnswer = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 184,
                            ImagePath = "Resources/QuestionOptionImages/q31o4.png",
                            IsAnswer = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 185,
                            ImagePath = "Resources/QuestionOptionImages/q31o5.png",
                            IsAnswer = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 186,
                            ImagePath = "Resources/QuestionOptionImages/q31o6.png",
                            IsAnswer = true,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 187,
                            ImagePath = "Resources/QuestionOptionImages/q32o1.png",
                            IsAnswer = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 188,
                            ImagePath = "Resources/QuestionOptionImages/q32o2.png",
                            IsAnswer = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 189,
                            ImagePath = "Resources/QuestionOptionImages/q32o3.png",
                            IsAnswer = true,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 190,
                            ImagePath = "Resources/QuestionOptionImages/q32o4.png",
                            IsAnswer = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 191,
                            ImagePath = "Resources/QuestionOptionImages/q32o5.png",
                            IsAnswer = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 192,
                            ImagePath = "Resources/QuestionOptionImages/q32o6.png",
                            IsAnswer = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 193,
                            ImagePath = "Resources/QuestionOptionImages/q33o1.png",
                            IsAnswer = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 194,
                            ImagePath = "Resources/QuestionOptionImages/q33o2.png",
                            IsAnswer = true,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 195,
                            ImagePath = "Resources/QuestionOptionImages/q33o3.png",
                            IsAnswer = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 196,
                            ImagePath = "Resources/QuestionOptionImages/q33o4.png",
                            IsAnswer = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 197,
                            ImagePath = "Resources/QuestionOptionImages/q33o5.png",
                            IsAnswer = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 198,
                            ImagePath = "Resources/QuestionOptionImages/q33o6.png",
                            IsAnswer = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 199,
                            ImagePath = "Resources/QuestionOptionImages/q34o1.png",
                            IsAnswer = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 200,
                            ImagePath = "Resources/QuestionOptionImages/q34o2.png",
                            IsAnswer = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 201,
                            ImagePath = "Resources/QuestionOptionImages/q34o3.png",
                            IsAnswer = true,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 202,
                            ImagePath = "Resources/QuestionOptionImages/q34o4.png",
                            IsAnswer = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 203,
                            ImagePath = "Resources/QuestionOptionImages/q34o5.png",
                            IsAnswer = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 204,
                            ImagePath = "Resources/QuestionOptionImages/q34o6.png",
                            IsAnswer = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 205,
                            ImagePath = "Resources/QuestionOptionImages/q35o1.png",
                            IsAnswer = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 206,
                            ImagePath = "Resources/QuestionOptionImages/q35o2.png",
                            IsAnswer = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 207,
                            ImagePath = "Resources/QuestionOptionImages/q35o3.png",
                            IsAnswer = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 208,
                            ImagePath = "Resources/QuestionOptionImages/q35o4.png",
                            IsAnswer = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 209,
                            ImagePath = "Resources/QuestionOptionImages/q35o5.png",
                            IsAnswer = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 210,
                            ImagePath = "Resources/QuestionOptionImages/q35o6.png",
                            IsAnswer = true,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 211,
                            ImagePath = "Resources/QuestionOptionImages/q36o1.png",
                            IsAnswer = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 212,
                            ImagePath = "Resources/QuestionOptionImages/q36o2.png",
                            IsAnswer = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 213,
                            ImagePath = "Resources/QuestionOptionImages/q36o3.png",
                            IsAnswer = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 214,
                            ImagePath = "Resources/QuestionOptionImages/q36o4.png",
                            IsAnswer = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 215,
                            ImagePath = "Resources/QuestionOptionImages/q36o5.png",
                            IsAnswer = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 216,
                            ImagePath = "Resources/QuestionOptionImages/q36o6.png",
                            IsAnswer = true,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 217,
                            ImagePath = "Resources/QuestionOptionImages/q37o1.png",
                            IsAnswer = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 218,
                            ImagePath = "Resources/QuestionOptionImages/q37o2.png",
                            IsAnswer = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 219,
                            ImagePath = "Resources/QuestionOptionImages/q37o3.png",
                            IsAnswer = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 220,
                            ImagePath = "Resources/QuestionOptionImages/q37o4.png",
                            IsAnswer = true,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 221,
                            ImagePath = "Resources/QuestionOptionImages/q37o5.png",
                            IsAnswer = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 222,
                            ImagePath = "Resources/QuestionOptionImages/q37o6.png",
                            IsAnswer = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 223,
                            ImagePath = "Resources/QuestionOptionImages/q38o1.png",
                            IsAnswer = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 224,
                            ImagePath = "Resources/QuestionOptionImages/q38o2.png",
                            IsAnswer = true,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 225,
                            ImagePath = "Resources/QuestionOptionImages/q38o3.png",
                            IsAnswer = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 226,
                            ImagePath = "Resources/QuestionOptionImages/q38o4.png",
                            IsAnswer = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 227,
                            ImagePath = "Resources/QuestionOptionImages/q38o5.png",
                            IsAnswer = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 228,
                            ImagePath = "Resources/QuestionOptionImages/q38o6.png",
                            IsAnswer = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 229,
                            ImagePath = "Resources/QuestionOptionImages/q39o1.png",
                            IsAnswer = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 230,
                            ImagePath = "Resources/QuestionOptionImages/q39o2.png",
                            IsAnswer = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 231,
                            ImagePath = "Resources/QuestionOptionImages/q39o3.png",
                            IsAnswer = true,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 232,
                            ImagePath = "Resources/QuestionOptionImages/q39o4.png",
                            IsAnswer = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 233,
                            ImagePath = "Resources/QuestionOptionImages/q39o5.png",
                            IsAnswer = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 234,
                            ImagePath = "Resources/QuestionOptionImages/q39o6.png",
                            IsAnswer = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 235,
                            ImagePath = "Resources/QuestionOptionImages/q40o1.png",
                            IsAnswer = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 236,
                            ImagePath = "Resources/QuestionOptionImages/q40o2.png",
                            IsAnswer = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 237,
                            ImagePath = "Resources/QuestionOptionImages/q40o3.png",
                            IsAnswer = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 238,
                            ImagePath = "Resources/QuestionOptionImages/q40o4.png",
                            IsAnswer = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 239,
                            ImagePath = "Resources/QuestionOptionImages/q40o5.png",
                            IsAnswer = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 240,
                            ImagePath = "Resources/QuestionOptionImages/q40o6.png",
                            IsAnswer = true,
                            QuestionId = 40
                        });
                });

            modelBuilder.Entity("IQTest.Core.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 1,
                            ImagePath = "Resources/QuestionImages/q1.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 1,
                            ImagePath = "Resources/QuestionImages/q2.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 1,
                            ImagePath = "Resources/QuestionImages/q3.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = 1,
                            ImagePath = "Resources/QuestionImages/q4.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = 2,
                            ImagePath = "Resources/QuestionImages/q5.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 6,
                            Difficulty = 2,
                            ImagePath = "Resources/QuestionImages/q6.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 7,
                            Difficulty = 2,
                            ImagePath = "Resources/QuestionImages/q7.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 8,
                            Difficulty = 2,
                            ImagePath = "Resources/QuestionImages/q8.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 9,
                            Difficulty = 3,
                            ImagePath = "Resources/QuestionImages/q9.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 10,
                            Difficulty = 3,
                            ImagePath = "Resources/QuestionImages/q10.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 11,
                            Difficulty = 3,
                            ImagePath = "Resources/QuestionImages/q11.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 12,
                            Difficulty = 3,
                            ImagePath = "Resources/QuestionImages/q12.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 13,
                            Difficulty = 4,
                            ImagePath = "Resources/QuestionImages/q13.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 14,
                            Difficulty = 4,
                            ImagePath = "Resources/QuestionImages/q14.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 15,
                            Difficulty = 4,
                            ImagePath = "Resources/QuestionImages/q15.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 16,
                            Difficulty = 4,
                            ImagePath = "Resources/QuestionImages/q16.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 17,
                            Difficulty = 5,
                            ImagePath = "Resources/QuestionImages/q17.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 18,
                            Difficulty = 5,
                            ImagePath = "Resources/QuestionImages/q18.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 19,
                            Difficulty = 5,
                            ImagePath = "Resources/QuestionImages/q19.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 20,
                            Difficulty = 5,
                            ImagePath = "Resources/QuestionImages/q20.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 21,
                            Difficulty = 6,
                            ImagePath = "Resources/QuestionImages/q21.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 22,
                            Difficulty = 6,
                            ImagePath = "Resources/QuestionImages/q22.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 23,
                            Difficulty = 6,
                            ImagePath = "Resources/QuestionImages/q23.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 24,
                            Difficulty = 6,
                            ImagePath = "Resources/QuestionImages/q24.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 25,
                            Difficulty = 7,
                            ImagePath = "Resources/QuestionImages/q25.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 26,
                            Difficulty = 7,
                            ImagePath = "Resources/QuestionImages/q26.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 27,
                            Difficulty = 7,
                            ImagePath = "Resources/QuestionImages/q27.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 28,
                            Difficulty = 7,
                            ImagePath = "Resources/QuestionImages/q28.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 29,
                            Difficulty = 8,
                            ImagePath = "Resources/QuestionImages/q29.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 30,
                            Difficulty = 8,
                            ImagePath = "Resources/QuestionImages/q30.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 31,
                            Difficulty = 8,
                            ImagePath = "Resources/QuestionImages/q31.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 32,
                            Difficulty = 8,
                            ImagePath = "Resources/QuestionImages/q32.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 33,
                            Difficulty = 9,
                            ImagePath = "Resources/QuestionImages/q33.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 34,
                            Difficulty = 9,
                            ImagePath = "Resources/QuestionImages/q34.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 35,
                            Difficulty = 9,
                            ImagePath = "Resources/QuestionImages/q35.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 36,
                            Difficulty = 9,
                            ImagePath = "Resources/QuestionImages/q36.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 37,
                            Difficulty = 10,
                            ImagePath = "Resources/QuestionImages/q37.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 38,
                            Difficulty = 10,
                            ImagePath = "Resources/QuestionImages/q38.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 39,
                            Difficulty = 10,
                            ImagePath = "Resources/QuestionImages/q39.png",
                            Name = "Choose the missing figure."
                        },
                        new
                        {
                            Id = 40,
                            Difficulty = 10,
                            ImagePath = "Resources/QuestionImages/q40.png",
                            Name = "Choose the missing figure."
                        });
                });

            modelBuilder.Entity("IQTest.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "admin@iqtest.com",
                            PasswordHash = new byte[] { 62, 192, 181, 24, 59, 191, 161, 174, 66, 53, 59, 125, 95, 149, 151, 0, 34, 250, 144, 112, 90, 251, 111, 174, 143, 10, 144, 7, 138, 100, 39, 192, 194, 155, 126, 32, 174, 196, 164, 69, 112, 70, 70, 251, 231, 235, 101, 174, 172, 158, 39, 19, 120, 66, 162, 117, 26, 96, 193, 35, 25, 178, 85, 152 },
                            PasswordSalt = new byte[] { 54, 90, 98, 108, 50, 118, 67, 80, 119, 51, 114, 79, 51, 54, 89, 73, 51, 121, 49, 106, 106, 68, 75, 106, 107, 89, 48, 48, 53, 89, 88, 107, 85, 53, 106, 100, 106, 114, 110, 53, 117, 107, 53, 50, 79, 48, 73, 115, 118, 74, 118, 65, 49, 65, 100, 53, 70, 65, 103, 57, 48, 85, 72, 110, 108, 74, 80, 120, 67, 97, 112, 55, 107, 106, 49, 78, 116, 113, 72, 69, 48, 84, 98, 80, 55, 101, 110, 105, 103, 78, 99, 105, 81, 78, 69, 106, 66, 48, 65, 72, 110, 68, 83, 51, 68, 66, 50, 119, 110, 106, 56, 54, 84, 83, 68, 67, 82, 101, 99, 55, 48, 54, 119, 116, 103, 66, 81, 70 },
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("IQTest.Core.Entities.Option", b =>
                {
                    b.HasOne("IQTest.Core.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
